# 1강

In [1]:
import numpy as np

In [2]:
a = np.array([2, 3, 4]) # 다차원 배열을 리스트로 생성
# 넘파이의 가장 기본이 되는 다차원 배열은 array() 함수와 리스트(또는 튜플)를 이용하여 생성한다.
print(f'a is {a} , and its type is {type(a)}')

a is [2 3 4] , and its type is <class 'numpy.ndarray'>


In [3]:
b = np.array((1,3,4)) # 튜플로도 선언할 수 있다.
print(f'b is {b} , and its type is {type(b)}')

b is [1 3 4] , and its type is <class 'numpy.ndarray'>


In [4]:
c = np.array([[2,3,4],[1,3,4]])
print(f'c is {c} , and its type is {type(c)}')

c is [[2 3 4]
 [1 3 4]] , and its type is <class 'numpy.ndarray'>


### 2차원 배열 

In [5]:
b = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]]) # 2차원 배열 생성
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 3차원 배열

In [6]:
c = np.array([ [[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8]],
[[ 9, 10, 11],[12, 13, 14],[15, 16, 17]],
[[18, 19, 20],[21, 22, 23],[24, 25, 26]]
]) # 3차원 배열 생성
print(c)
c[2][2][1]
# 인덱스가 0부터 시작함에 유의 !

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


25

### 다차원 배열의 속성들

In [7]:
a = np.array([[2,3,4]])

print(a)
# 형상
print(f'a.shape is {a.shape}')
# 차원
print(f'a.ndim is {a.ndim}')
# 자료형
print(f'a.dtype is {a.dtype}')
#원소의 크기(byte)
print(f'a.itemsize is {a.itemsize} (byte)')
# 원소의 개수
print(f'a.size is {a.size}')

# 형상 , 차원 , 자료형 , 원소의 크기(byte) , 원소의 개수
# 형상이 튜플로 리턴되는 이유 = immutable
# 형상이 (3,) 로 리턴되는 이유는 튜플에서 (3) 과 (3,)이 다르기 때문이다.
# ndim = "number of dimensions'

[[2 3 4]]
a.shape is (1, 3)
a.ndim is 2
a.dtype is int32
a.itemsize is 4 (byte)
a.size is 3


### ★ 원소가 1개인 튜플은 ,가 없으면 자료형으로 인식한다.

In [8]:
x = (3)
print(f'x is {x} , and its type is {type(x)}')

x is 3 , and its type is <class 'int'>


In [9]:
x = (3,)
print(f'now x is {x} , and its type is {type(x)}')

now x is (3,) , and its type is <class 'tuple'>


### 2개 부터는 ,가 없어도 된다.

In [10]:
x = (3,4)
print(f'x is {x} , and its type is {type(x)}')
x = (3,4,)
print(f'now x is {x} , and its type is {type(x)}')

x is (3, 4) , and its type is <class 'tuple'>
now x is (3, 4) , and its type is <class 'tuple'>


### 리스트의 연산

In [11]:
li = [11,22,33]
li1 = [2,3,4]

print(li)
print(li1)

# 리스트 사이에는 더하기가 성립한다.
print(li+li1)

# 실수 배도 가능하다.
print(li*2)

# 그러나, 리스트끼리 곱할 수는 없고
## TypeError: can't multiply sequence by non-int of type 'list'
### print(li*li1)

# 뺼 수도 없으며
## TypeError: unsupported operand type(s) for -: 'list' and 'list'
### print(li-li1)

# 나누기도 불가능하다.
## TypeError: unsupported operand type(s) for /: 'list' and 'list'
### print(li/li1)

[11, 22, 33]
[2, 3, 4]
[11, 22, 33, 2, 3, 4]
[11, 22, 33, 11, 22, 33]


### 배열의 연산

### 크기가 같은 배열(행렬)은 합 , 차 , 곱 , 나눗셈까지 정의된다.

In [11]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(f'a is {a}, b is {b}')
print(f'a + b is , {a + b}')
print(f'a - b is , {a - b}')

# 행렬곱과 다른 연산임에 유의
print(f'a * b is , {a * b}')
print(f'a / b is , {a / b}')
print(f'a * 2 is , {a * 2}')

a is [10 20 30], b is [1 2 3]
a + b is , [11 22 33]
a - b is , [ 9 18 27]
a * b is , [10 40 90]
a / b is , [10. 10. 10.]
a * 2 is , [20 40 60]


In [15]:
print(f'10 * a is , {10*a}')
print('★ 위 연산은 [10,10,10] * [10,20,30] 으로 변환되어 계산되는데, 이처럼 스칼라 10을 [10,10,10]의 벡터로 확장시키는 것을 브로드캐스팅(broadcasting)이라 한다.')
print(f'a + 10 is , {10 + a}')

a / 10

10 * a is , [100 200 300]
★ 위 연산은 [10,10,10] * [10,20,30] 으로 변환되어 계산되는데, 이처럼 스칼라 10을 [10,10,10]의 벡터로 확장시키는 것을 브로드캐스팅(broadcasting)이라 한다.
a + 10 is , [20 30 40]


array([1., 2., 3.])

배열끼리 차원이 달라도 broadcasting 해 연산한다.

In [14]:
li_a = [1,2,3]
li_b = [10,20,30]
print(f'li_a + li_b is {li_a + li_b}')
print(f'a + b is {a+b}')

li_a + li_b is [1, 2, 3, 10, 20, 30]
a + b is [11 22 33]


리스트 끼리의 덧셈은 extend지만 배열 끼리의 연산은 두 원소의 합이다.

In [15]:
arr_b = np.array([[10,20,30] , [1,2,3]])
arr_c = np.array([2,3,4])


print(f'arr_b + arr_c is {arr_b + arr_c}')

arr_b + arr_c is [[12 23 34]
 [ 3  5  7]]


### 초깃값을 지정하여 배열 생성

In [45]:
arr_zeros = np.zeros((1,3)) # 초깃값이 0인 1 *3 배열 생성
arr_ones = np.ones((2,4)) # 초깃값이 1인 2 * 4 배열 생성
#np.full((n,m),x) ## 초깃값이 x인 n*m 배열 생성

TypeError: Cannot interpret '3' as a data type

### 단위행렬 생성

In [17]:
arr_eye = np.eye(3) # 3 * 3 단위행렬 생성

### 연속적인 값을 가지는 다차원 배열 생성

range(n) : 0 ~ n-1 까지 n개!
range(m, n) : m ~ n-1까지 m-n개
range((m, n, s) : m ~ n까지 s만큼씩

In [18]:
m = 8
n = 7
# np.arange(m, n) # m부터 n 미만까지 연속적인 실수를 생성
# np.arange(m, n, step) ## m부터 n 미만까지 step만큼 건너뛰며 연속적인 실수를 생성

### np.linspace(시작, 끝, 생성 개수) : linear spaced, 시작값 ~ 끝 값까지의 구간에 대해(마지막 값 포함) 생성 개수 만큼의 값을 등간격으로 생성

In [19]:
np.linspace(0,10,5) # 0부터 10까지 등간격으로 5개 == 4개의 구간으로 -> 0, 2.5, 5, 7.5, 10
np.linspace(0,10) # num을 생략하면 default로 50개 생성 

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [49]:
a = np.array([[1,1],[2,2],[3,3]])
np.delete(a,np.s_[0:2],axis = 0)

array([[3, 3]])

In [39]:
a = np.array( [ [35, 23, 50], [71, 43, 19], [3, 0, 7] ] )
a.sort() # 배열의 오름차순 정렬, 디폴트 axis=1
a

array([[23, 35, 50],
       [19, 43, 71],
       [ 0,  3,  7]])

In [43]:
a = np.array( [ [35, 23, 50], [71, 43, 19], [3, 0, 7] ] )
a.sort(axis = 0) # 배열의 오름차순 정렬, 디폴트 axis=1
a

array([[ 3,  0,  7],
       [35, 23, 19],
       [71, 43, 50]])

In [29]:
arr_2d = np.array( [ [1, 2, 3], [4, 5, 6], [7, 8, 9], [0, 1, 2] ] )

arr_2d[0]

array([1, 2, 3])

### 배열의 차원

shape(arr) = (3,) -> 1차원 배열
             (1,3) -> 2차원 배열

### ★ 2차원 배열은 [[로 시작하여 ]]로 닫아진다.

In [20]:
print(np.shape([[2],[3],[5]])) # 3행 1열의 '2차원' 배열
print(np.shape([[1,2,3]])) # 1행 3열의 '2차원' 배열
print(np.shape([1,2,3])) # 1행 3열의 '1차원'배열, (3,)로 표시됨에 유의!


(3, 1)
(1, 3)
(3,)


### insert(배열,인덱스,삽입할 원소, axis = 축 설정(default = 1))

In [5]:
a = np.array([[1,3,4]])
n = np.insert(a,1,2) # a의 1번 인덱스(2번째)에 2라는 원소를 삽입허지만, ★ 원본 배열을 건들지 않고 새로운 배열을 return
print(n)

[1 2 3 4]


In [22]:
b = np.array([[1,1],[2,2],[3,3],[4,4]])

In [23]:
c = np.insert(b, 1, 4, axis = 0) # index = 1인 행에 삽입, broadcasting, [4,4]로 바꿔서 계산
print(c)
print("\n")

d = np.insert(b, 1, 4, axis = 1) # index = 1인 열에 삽입
print(d)
print("\n")

e = np.insert(b, 1, 4) # ★ 전체를 1차원 배열로 바꿔서 index = 1인 위치에 삽입
print(e)

[[1 1]
 [4 4]
 [2 2]
 [3 3]
 [4 4]]


[[1 4 1]
 [2 4 2]
 [3 4 3]
 [4 4 4]]


[1 4 1 2 2 3 3 4 4]


### insert - ★ 추가

In [55]:
a = np.array([[1,3,5],[6,8,10],[11,13,15]])
print(np.insert(a, [1,2], 0, axis = 1)) # a의 1번 index와 2번 index에 0을 삽입한다.
print("\n")
print(np.insert(a, [1,2], 0, axis = 0))

[[ 1  0  3  0  5]
 [ 6  0  8  0 10]
 [11  0 13  0 15]]


[[ 1  3  5]
 [ 0  0  0]
 [ 6  8 10]
 [ 0  0  0]
 [11 13 15]]


### ★ broadcasting은 Scalar 에 대해서만 적용된다

In [25]:
a = np.array([1,2,3])
b = np.array([1,1])
# print(a+b) ## ValueError: operands could not be broadcast together with shapes (3,) (2,) 

### ★ np.flip(배열) : 원소 뒤집기

In [61]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print("\n")

# 행 단위 뒤집기
print(np.flip(b, axis = 1))
print("\n")

# 열 단위 뒤집기
print(np.flip(b, axis = 0))

[[1 2 3]
 [4 5 6]]


[[6 5 4]
 [3 2 1]]


[[3 2 1]
 [6 5 4]]


[[4 5 6]
 [1 2 3]]


### delete 함수

In [30]:
a = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
print(type(a))
np.delete(a,[1,3],axis = 1) # (1,3)으로 캐스팅해도 된다, 암시적 형변환.

<class 'list'>


array([[ 1,  3,  5],
       [ 6,  8, 10],
       [11, 13, 15]])

### slice 함수

In [28]:
a = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
np.delete(a, slice(1,-1), axis = 1)

array([[ 1,  5],
       [ 6, 10],
       [11, 15]])

### cf) list.insert

In [29]:
li = []
li.insert(0,1) # insert(1,1)이여도 가능하다
li


[1]

### 참고 : https://kr.piliapp.com/symbol/subscript-superscript/