In [1]:
import numpy as np

### 배열의 index

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
np.linalg.det(arr) # 비가역행렬

0.0

In [4]:
arr[0] # 0행

array([1, 2, 3])

In [5]:
arr[0][2] # 0행 2열

3

In [6]:
arr[:, 1] # 1열만

array([2, 5, 8])

★ 3차원 배열의 indexing을 할 수 있어야 한다

In [7]:
arr_3d = np.array([[[0,1],[2,3],[4,5]],[[6,7],[8,9],[10,11]]])

In [8]:
arr_3d[0][2][1]

5

### 괄호를 사용해 indexing 할 수 있다.

In [9]:
arr[0,0] # == arr[0][0]

1

In [10]:
arr_3d[0,2,1] # == arr_3d[0][2][1]
arr_3d[0,2]

array([4, 5])

### 배열의 slicing : np.array[시작: 끝 : 스텝]

In [11]:
arr
arr[1:,0:2] # 1행부터 끝까지, 0열부터 2열까지

array([[4, 5],
       [7, 8]])

### 논리 인덱싱

In [12]:
np_array = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
np_array % 2 == 0 # 논리 연산자

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

[] -> 인덱스

In [13]:
np_array[np_array % 2 == 0] # 배열의 원소 중 조건을 만족하는 값만 출력

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 배열의 최대/최소/평균은 배열.메서드 형태로 제공된다.

결과값은 튜플로 출력된다.

In [70]:
np_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
np_array.max(), np_array.min(),np_array.mean()
# 최댓값, 최솟값, 평균

(16, 1, 8.5)

### 배열.astype() : 자료형 변경

In [15]:
np_array.astype(np.float64)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

### 배열.flatten() : 전부 1차원 배열로 변환

In [16]:
a = np.array([[1,1],[2,2],[3,3]])
a.flatten()

array([1, 1, 2, 2, 3, 3])

### 배열.T : 전치행렬 구하기

In [17]:
a.T

array([[1, 2, 3],
       [1, 2, 3]])

In [18]:
b = np.array([1,2,3])
c = b.T
print(np.shape(b))
print(np.shape(c))
# 행 벡터와 열 벡터를 구분하지 않음

(3,)
(3,)


### 정렬

리스트 : Timsort 사용

In [19]:
li = [1,5,5,7,8,8,8,4,8]
li.sort() # default : 오름차순 , method : Timsort
li

[1, 4, 5, 5, 7, 8, 8, 8, 8]

배열 : Quicksort 사용, default : 오름차순

In [20]:
arr = np.array([1,5,5,7,8,8,8,4,8])
arr_sorted = np.sort(arr) 

★ 내림차순 정렬하려면 오름차순으로 정렬 후 배열.flip()로 뒤집어야 한다.

In [21]:
b = np.sort(arr)
print(b)
c = np.flip(b)
print(c)

[1 4 5 5 7 8 8 8 8]
[8 8 8 8 7 5 5 4 1]


혹은, 오름차순으로 정렬한 배열을 거꾸로 인덱싱해서 사용한다.

In [22]:
np.sort(arr)[::-1]

array([8, 8, 8, 8, 7, 5, 5, 4, 1])

In [23]:
a = np.array([[35,23,50],[71,43,19],[3,0,7]])
a.sort(axis = 1) # 오름차순 정렬, default = 1(열 방향 == 행 단위 정렬)
a


array([[23, 35, 50],
       [19, 43, 71],
       [ 0,  3,  7]])

In [24]:
a = np.array([[35,23,50],[71,43,19],[3,0,7]])
a.sort(axis = 0) # 내림차순 정렬, 행 방향 == 열 단위 정렬.
a

array([[ 3,  0,  7],
       [35, 23, 19],
       [71, 43, 50]])

### 배열.append

In [25]:
li = [1,5,5]
li_1 = li.append(7) # 원본 배열을 변경하며, 새로운 배열을 리턴하지 않는다.
print(li)
print(li_1)

[1, 5, 5, 7]
None


In [26]:
a = np.array([1,2,3])
b = np.array([[4,5,6],[7,8,9]])
# 축이 명시되어 있지 않으면 2차원 배열을 1차원으로 변경
np.append(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.append(b,a)

array([4, 5, 6, 7, 8, 9, 1, 2, 3])

In [28]:
a = np.array([1,2,3]) # 1차원 배열
np.array([a]) # 2차원 배열

array([[1, 2, 3]])

In [29]:
a = np.array([1,2,3])
b = np.array([[4,5,6],[7,8,9]])
np.append([a],b,axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 배열.reshape : 배열의 형태 변경

In [30]:
y = np.arange(12)

In [31]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
np.shape(y)

(12,)

In [33]:
y.reshape(3,4) # 3행 3열로 변경, 원본 배열을 수정하지 않고 수정된 배열을 return.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
y.reshape(6, -1) # -1 :  데이터의 개수에 맞춰 자동으로 형태 결정, 원본 배열을 수정하지 않고 수정된 배열을 return.

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [36]:
np.shape(y)

(12,)

In [37]:
y.reshape(-1, 1) == y.reshape(12, 1)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [38]:
#y.reshape(7,2) ##  ValueError:cannot reshape array of size 12 into shape (7,2)

## 배열의 결합 : concatenate, vstack, hstack

### 배열끼리는 + 연산이 성립하므로 np.concatenate()를 통해 배열을 합쳐 줘야 한다.

In [13]:
import numpy as np

In [15]:
a = np.array([[1,2,3]])

In [17]:
b = np.array([[3,4,5]])

In [19]:
np.concatenate((a, b)) # default : axis = None

array([[1, 2, 3],
       [3, 4, 5]])

### 1차원 배열을 행방향으로 결합하려면 vstack를 사용해야 한다

In [42]:
#np.concatenate((a, b), axis = 1) ##AxisError: axis 1 is out of bounds for array of dimension 1

In [43]:
np.shape(a) # 1차원 배열

(3,)

In [44]:
np.shape([a]) # [a] = 1행 2열의 2차원 배열

(1, 3)

In [45]:
np.concatenate(([a],[b])) # default : 0, axis = 0, 열 방향 결합

array([[1, 2, 3],
       [3, 4, 5]])

In [46]:
np.concatenate((a,b)) # ??

array([1, 2, 3, 3, 4, 5])

### np.concatenate로 리스트와 1차원 배열을 결합할 수 있다

In [47]:
c = [6,7,8]
np.concatenate([b,c])

array([3, 4, 5, 6, 7, 8])

In [48]:
a = np.arange(10,18).reshape(2,4)  
b = np.arange(12).reshape(3,4)  
c = np.arange(8).reshape(2,4)  
d = list(range(4))

In [49]:
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [50]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
c

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [52]:
d

[0, 1, 2, 3]

In [53]:
np.concatenate((a, b)) # default : axis = 0, 행 방향 결합

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
# np.concatenate((a,d), axis = 0) 
## ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [55]:
np.concatenate((a,[d]),axis = 0)

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [ 0,  1,  2,  3]])

In [56]:
# np.concatenate((a,[d]), axis = 1) 
## ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [57]:
a = np.array([1,2,3])

In [58]:
b = np.array([3,4,5])

### vstack : 행 방향, return np.concatnate()

In [59]:
a

array([1, 2, 3])

In [60]:
b

array([3, 4, 5])

In [61]:
np.vstack([a, b]) # 행 방향 결합

array([[1, 2, 3],
       [3, 4, 5]])

배열과 리스트를 결합할 수 있다, 열의 개수가 같아야 결합 가능하다.

In [62]:
# np.vstack((a,[3,4]))
## all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [63]:
np.vstack((a,[3,4,5]))

array([[1, 2, 3],
       [3, 4, 5]])

In [64]:
np.hstack([a,b]) # 열 방향 결합

array([1, 2, 3, 3, 4, 5])

### np.r_[] : 베열을  결합

In [65]:
a = np.array([1,2,3])  
b = np.array([10,20,30])  
c = np.array([[1,2,3],[4,5,6]])  
d = np.array([[10,20,30],[40,50,60]])

In [66]:
np.r_[a,b] # 1차원 배열로 결합

array([ 1,  2,  3, 10, 20, 30])

In [67]:
np.r_[[a],[b]] # 2차원 배열끼리의 결합, 뭐가 충돌이라는 거지

array([[ 1,  2,  3],
       [10, 20, 30]])

In [68]:
np.r_[a,44,66,b] # 중간에 원소 삽입

array([ 1,  2,  3, 44, 66, 10, 20, 30])

★ [문제] 다음 두 2차원 배열의 수평 또는 수직결합이 가능한가?<br>
a=np.arange(5,1).reshape(2,3)  b=np.arange(4).reshape(2,2)  np.hstack(a,b)  np.vstack(a,b)  aray([5,6,7,0,1],  [8,9,10,2,3])<br> 
답: ValueEror

### np.c_[] : 배열을 열벡터로 변환시켜서 결합

In [69]:
np.c_[a,b] # 1차원 배열은 열벡터로 변환시켜서 결합하며, 그 결과는 2차원 배열이 된다

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

##### c_함수와 column_stack 함수는 1차원벡터를 열벡터로 인식하여 연결한다 2차원부터는 hstack함수와 동일한 역할을 한다.각 배열의 행의 수가 같아야 한다