In [1]:
import numpy as np

## ▣ 선다형 문제

### [문제1] Numpy에서 "브로드캐스팅(broadcasting)"이란 무엇인가?<br>
① 배열의 크기를 변경하는 방법<br>
② 두 배열 간의 자동으로 크기 조정을 통한 연산<br>
③ 배열의 요소를 자동으로 삭제하는 방법<br>
④ 배열의 데이터를 외부 파일로 저장하는 방법<br>

답) 2

In [2]:
a = np.array([10, 20, 30])
print(f'10 * a is , {10*a}')
print('★ 위 연산은 [10,10,10] * [10,20,30] 으로 변환되어 계산되는데, 이처럼 스칼라 10을 [10,10,10]의 벡터로 확장시키는 것을 브로드캐스팅(broadcasting)이라 한다.')

10 * a is , [100 200 300]
★ 위 연산은 [10,10,10] * [10,20,30] 으로 변환되어 계산되는데, 이처럼 스칼라 10을 [10,10,10]의 벡터로 확장시키는 것을 브로드캐스팅(broadcasting)이라 한다.


### [문제2] Numpy에서 배열의 차원을 확인하기 위한 속성은 무엇인가?<br>
① size<br>
② shape<br>
③ ndim<br>
④ dtype<br>

답) 3

In [3]:
a = np.array([[2,3,4]])
print(f'a.ndim is {a.ndim}')
# ndim = "number of dimensions'

a.ndim is 2


### [문제3] Numpy의 "다차원 배열"에서 축(axis)란 무엇인가?<br>
① 배열의 메모리 위치를 나타내는 값<br>
② 배열의 차원 또는 방향을 나타내는 값<br>
③ 배열의 크기를 나타내는 값<br>
④ 배열의 데이터 형식을 나타내는 값<br>

답) 2

axis = 0은 행 방향(수직 방향), <br>
axis = 1은 열 방향(수평 방향)이다.

### [문제4] 배열의 평균을 구하는 함수를 고르시오.<br>
① np.mean()<br>
② np.sum()<br>
③ np.median()<br>
④ np.average()<br>

답) 1

In [4]:
a = np.array([1,2,3,4])
a.mean()

2.5

### [문제5] 다차원 배열에서 축(axis)을 따라 성분을 삽입할 때 사용하는 함수를 고르시오.<br>
① np.concatenate()<br>
② np.insert()<br>
③ np.vstack()<br>
④ np.hstack()<br>

답) 1

In [5]:
b = np.array([[1,1],[2,2],[3,3],[4,4]])
print(b)
print("\n")

c = np.insert(b, 1, 4, axis = 0) # index = 1인 행에 삽입, broadcasting, [4,4]로 바꿔서 계산
print(c)
print("\n")

d = np.insert(b, 1, 4, axis = 1) # index = 1인 열에 삽입
print(d)
print("\n")

e = np.insert(b, 1, 4) # ★ 전체를 1차원 배열로 바꿔서 index = 1인 위치에 삽입
print(e)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


[[1 1]
 [4 4]
 [2 2]
 [3 3]
 [4 4]]


[[1 4 1]
 [2 4 2]
 [3 4 3]
 [4 4 4]]


[1 4 1 2 2 3 3 4 4]


### [문제6] 배열의 각 성분에 10을 더한 새로운 배열을 생성하는 코드를 고르시오.<br>
import numpy as np<br>
arr = np.array([1, 2, 3, 4])<br><br>
① arr + 10<br>
② np.add(arr, 10)<br>
③ arr.append(10)<br>
④ np.concatenate([arr, 10])<br>

답) 1, 2

In [6]:
import numpy as np
arr = np.array([1,2,3,4])

print(f'arr + 10 is {arr+10} \n') # broadcasting
print(f'np.add(arr,10) is {np.add(arr,10)}')

arr + 10 is [11 12 13 14] 

np.add(arr,10) is [11 12 13 14]


### [문제7] 배열의 특정 성분을 교체하려면 어떤 방법을 사용해야 하는가?<br>
① np.replace()<br>
② arr[인덱스] = 새로운 값<br>
③ arr.update()<br>
④ np.modify()<br>

답) 2

In [7]:
arr = np.array([1,2,3,4])
arr[0] = -1

print(f'arr is now {arr}')

arr is now [-1  2  3  4]


### [문제8] 다음 코드를 실행하면 출력되는 결과를 고르시오.<br>
import numpy as np<br>
arr1 = np.array([1, 2])<br>
arr2 = np.array([3, 4])<br>
result = np.r_[arr1, arr2]<br>
print(result) <br>

답) [1 2 3 4]

In [8]:
import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result = np.r_[arr1, arr2] # 1차원 배열로 결합
print(result)

[1 2 3 4]


### [문제9] 다음 코드의 출력 결과를 옳게 설명한 것을 고르시오.<br>
import numpy as np<br>
arr = np.array([[1, 2, 3], [4, 5, 6]])<br>
print(arr[0, : ])<br>

① 첫 번째 열의 모든 값<br>
② 첫 번째 행의 모든 값<br>
③ 첫 번째 열의 모든 값<br>
④ 두 번째 행의 모든 값<br>

답) 2

In [9]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, : ])

[1 2 3]


### [문제10] 다음 코드를 실행한 출력 결과를 고르시오.<br>
import numpy as np<br>
arr1 = np.array([[1, 2], [3, 4]])<br>
arr2 = np.array([[5, 6], [7, 8]])<br>
result = np.hstack([arr1, arr2])<br>
print(result)<br><br>
① [[1, 2, 5, 6], [3, 4, 7, 8]]<br>
② [[1, 2], [3, 4], [5, 6], [7, 8]]<br>
③ [1, 2, 3, 4, 5, 6, 7, 8]<br>
④ [[1, 5], [2, 6], [3, 7], [4, 8]]<br>

답) 1

In [10]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = np.hstack([arr1, arr2])
print(result)

[[1 2 5 6]
 [3 4 7 8]]


### [문제11] 다음 코드에서 arr[ : , -1]의 결과는 무엇인가?<br>
import numpy as np<br>
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])<br><br>
① 배열의 마지막 열<br>
② 배열의 마지막 행<br>
③ 배열의 첫 번째 열<br>
④ 배열의 첫 번째 행<br>

답) 1

In [11]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[:,-1]) # 뒤에서 1번째 열

[3 6 9]


## ▣ 진위형 문제 (True/False)

### [문제12] Numpy의 arange(m, n, step) 함수는 m부터 n까지의 값을 생성하고, <br>step은 각 성분 사이의 간격을 결정한다.
True / False

답) False

M부터 N-1까지 step만큼 진행시킨 값을 생성한다.

### [문제13] Numpy 배열에서 모든 성분은 같은 자료형이어야 한다.
True / False

답) True

### [문제14] np.append() 함수는 배열의 끝에 성분을 추가한다. 
True / False

답) True

## ▣ 단답형 문제

### [문제15] Numpy에서 배열의 모든 성분을 0으로 초기화하는 함수는 무엇인가?

답) np.zeros()

In [12]:
a = np.zeros((1,3)) # 1행 3열의 0으로 초기화된 배열 생성
print(a)

[[0. 0. 0.]]


### [문제16] Numpy 배열에서 값을 삭제하기 위한 함수는 무엇인가?

답) np.delete()

In [13]:
a = np.array([1,2,3])
np.delete(a,1)

array([1, 3])

## ▣ 완성형 (코드 입력하기)

### [문제17] 주어진 Numpy 배열 arr에서 모든 짝수 성분만 선택하는 코드를 작성하시오.<br>
import numpy as np<br>
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])<br>

답) arr[arr % 2 == 0]

In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10])

### [문제18] 11부터 25까지의 숫자를 가진 배열을 생성하고, 이 배열을 3 × 5 로 변환하는코드를 작성하시오.<br>
import numpy as np<br>
arr = __________________________<br>
reshaped_arr = _____________________<br><br>

답) <br>
arr = np.arange(11,26)<br>
reshaped_arr = arr.reshape(3,5)<br>

In [15]:
import numpy as np
arr = np.arange(11,26)
reshaped_arr = arr.reshape(3,5) # 수정된 배열을 return
print(reshaped_arr)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


 ### [문제19] hstack( ) 함수를 사용, 다음 2 × 2 두 배열을 수평으로 결합하는 코드를 작성하시오.<br><br>
import numpy as np<br>
arr1 = np.array([ [1, -2], [0, 5] ])<br>
arr2 = np.array([ [4, 5], [1, -2] ])<br>
combined_arr = ______________________<br><br>

답) combined_arr = np.hstack([arr1,arr2])

In [16]:
import numpy as np
arr1 = np.array([ [1, -2], [0, 5] ])
arr2 = np.array([ [4, 5], [1, -2] ])
combined_arr = np.hstack([arr1,arr2])
print(combined_arr)

[[ 1 -2  4  5]
 [ 0  5  1 -2]]


### [문제20] vstack( ) 함수를 사용하여, 두 배열을 수직으로 결합하는 코드를 작성하시오.<br><br>
import numpy as np<br>
arr1 = np.array([11, 12, 13])<br>
arr2 = np.array([41, 51, 61])<br>
combined_arr = ___________________<br><br>

답) combined_arr = np.vstack([arr1,arr2])

In [3]:
import numpy as np
arr1 = np.array([11, 12, 13])
arr2 = np.array([41, 51, 61])
combined_arr = np.vstack([arr1,arr2])
print(combined_arr)

[[11 12 13]
 [41 51 61]]


In [5]:
np.hstack([arr1,arr2])

TypeError: hstack() takes 1 positional argument but 2 were given

### [문제21] np.r_을 사용하여 출력 결과처럼, 다음 두 배열을 세로로 결합하는 코드를 작성하시오.<br><br>
import numpy as np<br>
arr1 = np.array([1, 2])<br>
arr2 = np.array([3, 4])<br>
결과: [[1, 2], [3, 4]]<br><br>

답)
res = np.r_[[arr1],[arr2]]

In [9]:
import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
res = np.r_[[arr1],[arr2]]
print(f'결과 : {res}')

결과 : [1 2 3 4]


### [문제22] 다음 배열을 역순으로 만들기 위한 flip() 함수를 사용하는 코드를 완성하시오. <br><br>
import numpy as np<br>
arr = np.array([4, 5, 6, 7, 8])<br>
flipped_arr = ___________<br><br>

답) flipped_arr = np.flip(arr)

In [20]:
import numpy as np
arr = np.array([4, 5, 6, 7, 8])
flipped_arr = np.flip(arr)
print(flipped_arr)

[8 7 6 5 4]


### [문제23] 배열에서 특정 값을 삽입하기 위해 insert() 함수를 사용한다. 다음 코드를 완성하시오.<br><br>
import numpy as np<br>
arr = np.array([1, 2, 3])<br>
new_arr = __________________________<br>
출력결과: array([1, 100, 2, 3])<br><br>

답) new_arr = np.insert(arr,1,100)

In [21]:
import numpy as np
arr = np.array([1, 2, 3])
new_arr = np.insert(arr,1,100)

new_arr

array([  1, 100,   2,   3])

### [문제24] 다음 2차원 배열에서 행은 1번째부터 2번째까지, 열은 1번째부터 2번째까지의 부분 배열을 추출하는 코드를 작성하시오.<br>
import numpy as np<br><br>
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])<br>
sub_array = _____________________________<br><br>

답) sub_array = arr[0:2,0:2]

In [22]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_array = arr[0:2,0:2] # n-1
print(sub_array)

[[1 2]
 [4 5]]


### [문제25] 다음 배열에서 첫 번째 열을 추출하는 코드를 완성하시오.<br><br>
import numpy as np<br>
arr = np.array([[1, 2, 3], [4, 5, 6]])<br>
first_col = ____________________<br><br>

답) frist_col = arr[:,0]

In [23]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
first_col = arr[:,0]
print(first_col)

[1 4]


### [문제26] 다음 배열의 마지막 행을 추출하는 코드를 작성하시오.<br><br>
import numpy as np<br>
arr = np.array([[1, 2, 3], [4, 5, 6]])<br>
last_row = _____________________<br><br>

답) last_row = arr[-1,:]

In [24]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
last_row = arr[-1,:] # // arr[1,:]
print(last_row)

[4 5 6]


### [문제27] 다음 3차원 배열에서 모든 2D 배열의 첫 번째 행을 추출하는 코드를 작성하시오. <br><br>
import numpy as np<br>
arr = np.array([ [[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]] ])<br>
first_rows = ______________________<br><br>

답) first_rows = arr[:,0,:]

In [25]:
import numpy as np
arr = np.array([ [[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]] ])
first_rows = arr[:,0,:] # 바깥 쪽 부터 인덱싱
print(first_rows)

[[ 1  2]
 [ 5  6]
 [ 9 10]]


### [문제28] np.concatenate() 함수를 사용하여, 두 배열을 로 세로로 결합하는 코드를 완성하시오. <br><br>
import numpy as np<br>
arr1 = np.array([[1, 2], [3, 4]])<br>
arr2 = np.array([[5, 6]])<br>
result = ________________________________<br>
print(result)<br><br>
출력결과 [[1 2]<br>
[3 4]<br>
[5 6]]<br><br>

답) result = np.concatenate((arr1,arr2),axis = 0)

In [26]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
result = np.concatenate((arr1,arr2),axis = 0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


## ▣ 다양한 방법으로 조건을 만족하는 코드 선택 문제
### [문제29] 다음 2차원 배열에서 모든 성분이 5보다 큰 값을 추출하는 코드를 고르시오.<br><br>
import numpy as np<br>
arr = np.array([[1, 6, 3], [4, 7, 8], [9, 2, 5]])<br><br>
① arr[arr > 5]<br>
② arr[arr < 5]<br>
③ arr[arr >= 5]<br>
④ arr[arr != 5]<br><br>

답) 1 

In [27]:
import numpy as np
arr = np.array([[1, 6, 3], [4, 7, 8], [9, 2, 5]]) 
print(f'arr[arr > 5] is {arr[arr > 5]}') # 5 초과!

arr[arr > 5] is [6 7 8 9]


### [문제30] 다음 2차원 배열에서 첫 번째 행의 성분에서 짝수만 추출하는 코드를 모두 고르시오. <br><br>
import numpy as np<br>
arr = np.array([[1, 2, 3], [4, 5, 6]])<br><br>
① arr[0, arr[0] % 2 == 0]<br>
② arr[0, arr[0] % 2 != 0]<br>
③ arr[0][arr[0] % 2 == 0]<br>
④ arr[0][arr[0] % 2 != 0]<br><br>

답) 3

In [28]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, arr[0] % 2 == 0]
print(f'arr[0][arr[0] % 2 == 0] is {arr[0][arr[0] % 2 == 0]}')

arr[0][arr[0] % 2 == 0] is [2]


### [문제31] 다음 3차원 배열에서 두 번째 2D 배열의 첫 번째 행을 추출하는 코드를 모두 고르시오.<br><br>
import numpy as np<br>
arr = np.array([ [[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]] ])<br><br>
① arr[1, 0, : ]<br>
② arr[1, : , 0]<br>
③ arr[1, 0, : ]<br>
④ arr[1, 0, : ]<br><br>

답) arr[1,0,:]

In [29]:
import numpy as np
arr = np.array([ [[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]] ])
arr[1,0,:] # 가장 바깥 괄호부터 인덱싱

array([5, 6])

## ▣ 코드 작성 및 출력 결과 작성/오류 찾기<br>
### [문제32] 다음 코드의 결과를 작성하시오.<br><br>
arr1 = np.array([1, 2])<br>
arr2 = np.array([3, 4])<br>
result1 = np.c_[arr1, arr2]<br><br>

답) [[1,3],[2,4]]

In [30]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result1 = np.c_[arr1, arr2]
print(result1)

[[1 3]
 [2 4]]


### [문제33] 다음 코드의 출력 결과를 설명하시오. <br><br>
import numpy as np<br>
arr = np.array([[1, 2, 3], [4, 5, 6]])<br>
print(arr[ : : 2, : : 2])<br><br>

답) [[1, 3]] <br><br>
step = 2이므로 첫 번째 행만 인덱싱되고 <br>
step = 2이므로 첫 번째, 세 번째 열만 인덱싱된다.<br>

In [31]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[ : : 2, : : 2]) # start, stop, step 

[[1 3]]


### [문제34] 다음 코드 중 올바르지 않은 부분을 고르세요. <br><br>
import numpy as np<br>
arr1 = np.arange(10).reshape(2, 5)<br>
arr2 = np.arange(15).reshape(3, 5)<br>
result = arr1 + arr2<br><br>

답) 크기가 다른 배열끼리 덧셈이 성립할 수 없으므로, arr1과 arr2의 차원을 맞춰 줘야 한다.

In [32]:
# import numpy as np
# arr1 = np.arange(10).reshape(2, 5)
# arr2 = np.arange(15).reshape(3, 5)
# result = arr1 + arr2

# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# Cell In[109], line 4
#       2 arr1 = np.arange(10).reshape(2, 5)
#       3 arr2 = np.arange(15).reshape(3, 5)
# ----> 4 result = arr1 + arr2

# ValueError: operands could not be broadcast together with shapes (2,5) (3,5) 

### [문제35] 다음 코드 중 올바르지 않은 부분을 고르시오. <br><br>
import numpy as np<br>
arr1 = np.array([[1, 2], [3, 4]])<br>
arr2 = np.array([[5, 6]])<br>
combined = np.concatenate((arr1, arr2), axis=1)<br><br>

답) combined = np.concatenate((arr1, arr2), axis=1)<br>
np.concatenate로 2행 2열의 배열과 1행 2열의 배열끼리 수평으로(열 방향으로) 결합시킬 수 없다.

In [33]:
# import numpy as np
# arr1 = np.array([[1, 2], [3, 4]])
# arr2 = np.array([[5, 6]])
# combined = np.concatenate((arr1, arr2), axis= 1)

# ValueError: all the input array dimensions except for the concatenation axis must match exactly, 
# but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

### [문제36] 1부터 10까지의 숫자를 포함하는 1차원 배열을 생성하고, 배열의 평균, 최댓값, 최솟값을 계산하는 코드를 작성하시오.

답) <br>
arr = np.arange(1,11) <br>
arr.mean(), arr.max(), arr.min() # 평균, 최댓값, 최솟값

In [34]:
arr = np.arange(1,11)
print(f'arr is {arr} \n')
print(f'arr.mean() is {arr.mean()}') # 평균
print(f'arr.max() is {arr.max()}') # 최댓값
print(f'arr.mean() is {arr.mean()}') # 최솟값

arr is [ 1  2  3  4  5  6  7  8  9 10] 

arr.mean() is 5.5
arr.max() is 10
arr.mean() is 5.5


### [문제37] 3 × 3 크기의 배열을 생성하고, 배열의 2행 2열 성분만 0으로 설정하는 코드를 작성하시오.

답) <br>
arr = np.arange(1,10).reshape(3,3) # 1 ~ 9까지의 초깃값을 가지는 3 x 3 크기의 배열 생성 <br>
arr[1][1] = 0 # 2번째 행, 2번째 열을 0으로 설정

In [35]:
arr = np.arange(1,10).reshape(3,3)
arr[1][1] = 0 
print(f'arr is {arr}')

arr is [[1 2 3]
 [4 0 6]
 [7 8 9]]


# 끝! 